export { serviceContainer, useService, registerService } from './serviceContainer'
export { registerAllServices, getTabService } from './serviceFactory'
export { SERVICE_IDENTIFIERS } from '@/types/services'

export { TabService, useTabService } from './tabService'
export { electronService } from './electron/ElectronService'
export { ElectronEventHandler } from './electron/ElectronEventHandler'
export { useI18n, t } from './i18n'
export { useClipboard } from './clipboard'
export { useCapture } from './capture'
export { useThemeService } from './theme/ThemeService'
export { useRecentFilesService } from './recentFiles/RecentFilesService'
export { errorManager } from './errorHandler'
export { imagePathResolver } from './imagePathResolver'
export { xssSanitizer } from './xssSanitizer'